apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: credify-frontend
  name: credify-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: credify-frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: credify-frontend
    spec:
      containers:
      - image: gcr.io/sunlit-core-307817/reactimage
        name: reactimage
        imagePullPolicy: Always
        resources: {}
status: {}
