apiVersion: apps/v1
kind: Deployment
metadata:
  name: credify-backend
spec:
  selector:
    matchLabels:
      app: credify-backend
  template:
    metadata:
      labels:
        app: credify-backend
    spec:
      containers:
      - image: gcr.io/sunlit-core-307817/credifydjango
        name: credifydjango
        imagePullPolicy: Always
        # ... other container configuration
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: database
      - name: cloud-sql-proxy
        # It is recommended to use the latest version of the Cloud SQL proxy
        # Make sure to update on a regular schedule!
        image: gcr.io/cloudsql-docker/gce-proxy:1.17
        command:
          - "/cloud_sql_proxy"

          # If connecting from a VPC-native GKE cluster, you can use the
          # following flag to have the proxy connect over private IP
          # - "-ip_address_types=PRIVATE"

          # Replace DB_PORT with the port the proxy should listen on
          # Defaults: MySQL: 3306, Postgres: 5432, SQLServer: 1433
          - "-instances=sunlit-core-307817:us-central1:credifydb=tcp:5432"

          # This flag specifies where the service account key can be found
          - "-credential_file=/secrets/service_account.json"
        securityContext:
          # The default Cloud SQL proxy image runs as the
          # "nonroot" user and group (uid: 65532) by default.
          runAsNonRoot: true
        volumeMounts:
        - name: sa-secret-volume
          mountPath: /secrets/
          readOnly: true
      volumes:
      - name: sa-secret-volume
        secret:
          secretName: sa-secret
